spring:
  thymeleaf:
    cache: false
  data:
    mongodb:
      database: theater_test
      port: 27017
      host: localhost
  mail:
    host: smtp.gmail.com
    username: '*****'
    password: '*****'
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
server:
  error:
    path: /error
    whitelabel:
      enabled: false

support:
  email: theater@gmail.com

